apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  selector:
    matchLabels:
      app: postgresql-db # has to match .spec.template.metadata.labels
  serviceName: "postgresql-db-service"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgresql-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgresql-db
          image: postgres:latest
          
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
        
      spec:
        accessModes: ["ReadWriteOnce"]
        #storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
